name: flutter_icons_plus
description: Customizable Icons for Flutter with over 3K+ icons. It is the null safe version of the
  flutter_icons package
version: 1.0.1
repository: https://github.com/Bakri-Alkhateeb/flutter_icons_plus

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

flutter:
  fonts:
    - family: Ionicons
      fonts:
        - asset: fonts/Ionicons.ttf
    - family: AntDesign
      fonts:
        - asset: fonts/AntDesign.ttf
    - family: FontAwesome
      fonts:
        - asset: fonts/FontAwesome.ttf
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons.ttf
    - family: Entypo
      fonts:
        - asset: fonts/Entypo.ttf
    - family: EvilIcons
      fonts:
        - asset: fonts/EvilIcons.ttf
    - family: Feather
      fonts:
        - asset: fonts/Feather.ttf
    - family: Foundation
      fonts:
        - asset: fonts/Foundation.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: fonts/MaterialCommunityIcons.ttf
    - family: Octicons
      fonts:
        - asset: fonts/Octicons.ttf
    - family: SimpleLineIcons
      fonts:
        - asset: fonts/SimpleLineIcons.ttf
    - family: Zocial
      fonts:
        - asset: fonts/Zocial.ttf
    - family: FontAwesome5
      fonts:
        - asset: fonts/FontAwesome5_Regular.ttf
    - family: FontAwesome5_Brands
      fonts:
        - asset: fonts/FontAwesome5_Brands.ttf
    - family: FontAwesome5_Solid
      fonts:
        - asset: fonts/FontAwesome5_Solid.ttf
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons.ttf
